### ISSUE TITLE
TimeRangeException for experiments in Event Density view

### ISSUE THREAD

**Issue by bhufmann** [eclipse-tracecompass/org.eclipse.tracecompass#18]
With commit: 15d6f25 I get the following exception for the `Event Density` view when opening an experiment:

```
Exception in thread "Line chart update" org.eclipse.tracecompass.statesystem.core.exceptions.TimeRangeException: Time conditions 1487359244565151799 is lower than state system start time: 1487359244680159245
	at org.eclipse.tracecompass.internal.statesystem.core.StateSystem.query2D(StateSystem.java:652)
	at org.eclipse.tracecompass.internal.statesystem.core.StateSystem.query2D(StateSystem.java:634)
	at org.eclipse.tracecompass.tmf.core.statistics.TmfStateStatistics.histogramQuery(TmfStateStatistics.java:129)
	at org.eclipse.tracecompass.internal.tmf.core.histogram.HistogramDataProvider.fetchXY(HistogramDataProvider.java:128)
	at org.eclipse.tracecompass.tmf.core.model.xy.TmfTreeXYCompositeDataProvider.getXyResponses(TmfTreeXYCompositeDataProvider.java:187)
	at org.eclipse.tracecompass.tmf.core.model.xy.TmfTreeXYCompositeDataProvider.fetchXY(TmfTreeXYCompositeDataProvider.java:136)
	at org.eclipse.tracecompass.tmf.ui.viewers.xychart.linechart.TmfCommonXAxisChartViewer$UpdateThread.updateData(TmfCommonXAxisChartViewer.java:384)
	at org.eclipse.tracecompass.tmf.ui.viewers.xychart.linechart.TmfCommonXAxisChartViewer$UpdateThread.run(TmfCommonXAxisChartViewer.java:350)
```

**Comment by bhufmann** [comment]
@arfio could this exception be caused by the change #6?

**Comment by arfio** [comment]
Yes it was, I was sure I fixed this issue but cannot find where, I must have removed the fix at some point.

**Comment by bhufmann** [comment]
Fixed with above pull request.
